# Generated by Django 4.0.1 on 2024-10-29 16:45

from django.db import migrations, models
import django.utils.timezone

import pong_service_app.api.themes

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PongGame',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('users', models.JSONField(default=list)),
                ('winner_id', models.IntegerField(default=-1)),
                ('score', models.JSONField(default=list)),
                ('type', models.CharField(choices=[('local1v1', 'Local 1v1'), ('1v1', '1v1'), ('arcade', 'Arcade'), ('tournament', 'Tournament')], default='1v1', max_length=255)),
                ('status', models.CharField(choices=[('init', 'Init'), ('started', 'Started'), ('finished', 'Finished'), ('forfaited', 'Forfaited')], default='init', max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('map_theme', models.JSONField(default=pong_service_app.api.themes.get_default_theme)),
            ],
        ),
        migrations.CreateModel(
            name='PongUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('game_history', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PongUserStats',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('loses', models.IntegerField(default=0)),
            ],
        ),
    ]