# Generated by Django 4.0.1 on 2024-10-29 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
       ('pong_service_app', '0002_ponguser_last_game'), 
    ]

    operations = [
        migrations.AddField(
            model_name='ponggame',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
