# Generated by Django 4.0.1 on 2024-10-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_service_app', '0002_ponguser_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PongGame',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('users', models.JSONField(default=list)),
                ('winner_id', models.IntegerField()),
                ('score', models.JSONField(default=list)),
                ('type', models.CharField(choices=[('1v1', '1v1'), ('tournament', 'Tournament')], default='1v1', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PongUserStats',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('loses', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ponguser',
            name='name',
        ),
        migrations.AddField(
            model_name='ponguser',
            name='game_history',
            field=models.JSONField(default=list),
        ),
    ]
