# Generated by Django 4.0.1 on 2024-10-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_service_app', '0003_ponggame_ponguserstats_remove_ponguser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponguser',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
