# Generated by Django 4.0.1 on 2025-01-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_service_app', '0004_alter_tournament_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentparticipant',
            name='eliminated',
            field=models.BooleanField(default=False),
        ),
    ]
