# Generated by Django 4.0.1 on 2024-10-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_service_app', '0004_alter_ponguser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponggame',
            name='winner_id',
            field=models.IntegerField(blank=True),
        ),
    ]
