# Generated by Django 4.0.1 on 2024-10-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_service_app', '0005_alter_ponggame_winner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggame',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('stated', 'Started'), ('finished', 'Finished')], default='init', max_length=255),
        ),
        migrations.AlterField(
            model_name='ponggame',
            name='winner_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='ponguserstats',
            name='loses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ponguserstats',
            name='played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ponguserstats',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
