# Generated by Django 4.0.1 on 2025-01-31 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pong_service_app', '0005_tournamentparticipant_eliminated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='pong_service_app.tournament'),
        ),
    ]
