# Generated by Django 4.0.1 on 2025-02-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_service_app', '0006_alter_tournamentparticipant_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponguser',
            name='last_game',
            field=models.IntegerField(default=-1),
        ),
    ]
