# Generated by Django 4.0.1 on 2024-10-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_service_app', '0006_ponggame_status_alter_ponggame_winner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponggame',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('finished', 'Finished')], default='init', max_length=255),
        ),
        migrations.AlterField(
            model_name='ponggame',
            name='type',
            field=models.CharField(choices=[('local1v1', 'Local 1v1'), ('1v1', '1v1'), ('tournament', 'Tournament')], default='1v1', max_length=255),
        ),
    ]
