# Generated by Django 4.0.1 on 2024-10-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_service_app', '0007_alter_ponggame_status_alter_ponggame_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponggame',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('started', 'Started'), ('finished', 'Finished')], default='init', max_length=255),
        ),
    ]
