# Generated by Django 4.0.1 on 2025-02-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_service_app', '0007_alter_ponguser_last_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='total_rounds',
            field=models.IntegerField(default=1),
        ),
    ]
