# Generated by Django 4.0.1 on 2024-10-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_service_app', '0008_alter_ponggame_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponggame',
            name='type',
            field=models.CharField(choices=[('local1v1', 'Local 1v1'), ('1v1', '1v1'), ('arcade', 'Arcade'), ('tournament', 'Tournament')], default='1v1', max_length=255),
        ),
    ]
