# Generated by Django 4.0.1 on 2025-02-06 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pong_service_app', '0010_alter_tournament_total_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='pong_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pong_service_app.ponggame'),
        ),
    ]
