# Generated by Django 4.0.1 on 2025-02-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_service_app', '0011_tournamentmatch_pong_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggame',
            name='tournament_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
