services:
  website:
    container_name: website
    build: ./website
    ports:
      - ${WEBSITE_PORT}:${WEBSITE_PORT}
    volumes:
      - type: bind
        source: ./website/src
        target: /usr/share/nginx/html

  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    restart: always
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    environment:
      PROJECT_NAME: "api_gateway"
      APP_PORT: ${API_GATEWAY_PORT}
      DJANGO_SUPERUSER_EMAIL: ${ADMIN_EMAIL}
      DJANGO_SUPERUSER_USERNAME: ${ADMIN_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - type: bind
        source: ./api_gateway
        target: /api_gateway

  users_service:
    build: ./users_service
    container_name: users_service
    restart: always
    ports:
      - ${USERS_SERVICE_PORT}:${USERS_SERVICE_PORT}
    depends_on:
      users_service_database:
        condition: service_healthy
    environment:
      PROJECT_NAME: "users_service"
      APP_PORT: ${USERS_SERVICE_PORT}
      API_42_UID: ${API_42_UID}
      API_42_SECRET: ${API_42_SECRET}
      DATABASE_HOST: ${USERS_DB_CONTAINER_NAME}
      DATABASE_PORT: ${USERS_DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${ADMIN_EMAIL}
      DJANGO_SUPERUSER_USERNAME: ${ADMIN_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - type: bind
        source: ./users_service
        target: /users_service

  users_service_database:
    image: postgres:latest
    container_name: ${USERS_DB_CONTAINER_NAME}
    restart: always
    ports:
      - ${USERS_DB_PORT}:${USERS_DB_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: [ "postgres", "-c", "port=${USERS_DB_PORT}" ]
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -p ${USERS_DB_PORT} -d $$POSTGRES_DB"
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data


networks:
  # suggestion:
  # isolate services, forcing the site frontend to contact the API Gateway only
  services-network:
    driver: bridge
  # linking website with api_gateway only
  website-network:
    driver: bridge

volumes:
  website:
  api_gateway:
  users_service:
  pgdata:
