# Generated by Django 5.0.6 on 2024-07-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_service_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='github',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='lang',
            field=models.CharField(default='en', max_length=2),
        ),
    ]
