# Generated by Django 4.0.1 on 2024-08-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_service_app', '0003_friend_friend_unique_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='status_message',
            field=models.CharField(default='Hello World', max_length=128),
        ),
    ]
