# Generated by Django 4.0.1 on 2024-08-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_service_app', '0005_alter_usersettings_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfidentialitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends_only', 'Friends Only')], default='public', max_length=32)),
                ('show_fullname', models.BooleanField(default=True)),
                ('show_email', models.BooleanField(default=True)),
            ],
        ),
    ]
