# Generated by Django 4.0.1 on 2024-08-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_service_app', '0006_userconfidentialitysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfidentialitysettings',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=32),
        ),
    ]
