# Generated by Django 4.0.1 on 2025-02-01 15:59

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users_service_app', '0009_alter_usersettings_avatar'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('friend')), _negated=True), name='prevent_self_friendship'),
        ),
    ]
