# Generated by Django 4.0.1 on 2025-02-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_service_app', '0010_friend_prevent_self_friendship'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friend',
            name='unique_friendship',
        ),
        migrations.RemoveConstraint(
            model_name='friend',
            name='prevent_self_friendship',
        ),
    ]
