# Generated by Django 4.0.1 on 2025-02-10 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_service_app', '0011_remove_friend_unique_friendship_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('user', 'friend')},
        ),
    ]
