# Generated by Django 4.0.1 on 2024-12-02 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pong_service_app', '0002_ponguser_last_game'),
        ('tournamentParticipants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentparticipants',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pong_service_app.ponguser'),
        ),
    ]
