# Generated by Django 4.0.1 on 2024-12-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentdata',
            name='tournamentWinner',
        ),
    ]
