# Generated by Django 4.0.1 on 2024-12-02 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pong_service_app', '0002_ponguser_last_game'),
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobbydata',
            name='lobbyWinner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_lobby', to='pong_service_app.ponguser'),
        ),
        migrations.AlterField(
            model_name='lobbydata',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_player1', to='pong_service_app.ponguser'),
        ),
        migrations.AlterField(
            model_name='lobbydata',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_player2', to='pong_service_app.ponguser'),
        ),
    ]
