# Generated by Django 4.0.1 on 2025-01-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pong_service_app', '0002_ponguser_last_game'),
        ('tournamentPairings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentpairingdata',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_id', to='pong_service_app.ponguser'),
        ),
        migrations.AddField(
            model_name='tournamentpairingdata',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_id', to='pong_service_app.ponguser'),
        ),
        migrations.AddField(
            model_name='tournamentpairingdata',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_id', to='pong_service_app.ponguser'),
        ),
    ]
